--II. Run second
-- top artifacts/dictionaries
delete CTUSR.RULE;
delete CTUSR.RULESET;
delete CTUSR.SERVICE;
delete CTUSR.ENDPOINT;
delete CTUSR.OBJECT_PARAMETER;
delete CTUSR.POLICY;
delete CTUSR.APPLICATION;
delete CTUSR.EVENT;
delete CTUSR.MESSAGE;
delete CTUSR.POLICY_PROVIDER;
delete CTUSR.COMPOSITION_ROLE;
delete CTUSR.PROTOCOL;
delete CTUSR.ENDPOINT_TYPE;
delete CTUSR.MEP;
delete CTUSR.OPERATION_TYPE;
delete CTUSR.PARAMETER;
delete CTUSR.OBJECT;
delete CTUSR.GU_LOCATION;
delete CTUSR.BU_LOCATION;
delete CTUSR.RULE_VERIFICATION;
delete CTUSR.RULE_AGGREGATION;
delete CTUSR.SERVICE_MODEL;
delete CTUSR.SERVICE_ENGINE;
delete CTUSR.PATTERN;
delete CTUSR.EVENT_MESSAGETYPE;
commit;