--------------------------------------------------------
--  File created - Tuesday-February-21-2012   
--------------------------------------------------------
REM INSERTING into PARAMETER
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (1,'EVENT_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (2,'MESSAGE_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (3,'OBLECT_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (4,'PROCESS_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (5,'RULE_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (6,'RULESET_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (7,'APPLICATION_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (8,'ENDPOINT_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (9,'PROTOCOL_ID','NUMBER',null);
Insert into CTUSR.PARAMETER (PARAMETER_ID,PARAMETER_NAME,PARAMETER_TYPE,PARAMETER_DESCRIPTION) values (10,'MEP_ID','NUMBER',null);
