REM INSERTING into MEP
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (1,'in-out','The in-out pattern, comparable to the request-response MEP (and equivalent to the WSDL 1.1 request-response operation).');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (2,'out-in','The out-in pattern, which is the reverse of the previous patternwhere the service provider initiates the exchange by transmitting the request. (Equivalent to the WSDL 1.1 solicit-response operation.)');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (3,'in-only ','The in-only pattern, which essentially supports the standard fire-and-forget MEP. (Equivalent to the WSDL 1.1 one-way operation.)');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (4,'out-only ','The out-only pattern, which is the reverse of the in-only pattern. It is used primarily in support of event notification. (Equivalent to the WSDL 1.1 notification operation.)');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (5,'robust in-only','The robust in-only pattern, a variation of the in-only pattern that provides the option of launching a fault response message as a result of a transmission or processing error');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (6,'robust out-only','The robust out-only pattern, which, like the out-only pattern, has an outbound message initiating the transmission. The difference here is that a fault message can be issued in response to the receipt of this message.');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (7,'in-optional-out','The in-optional-out pattern, which is similar to the in-out patternwith one exception. This variation introduces a rule stating that the delivery of a response message is optional and should therefore not be expected by the service requestor that originated the communication. This pattern also supports the generation of a fault message.');
Insert into CTUSR.MEP (MEP_ID,MEP_NAME,MEP_DESCRIPTION) values (8,'out-optional-in','The out-optional-in pattern is the reverse of the in-optional-out pattern, where the incoming message is optional. Fault message generation is again supported.');
