REM INSERTING into APPLICATION
Insert into CTUSR.APPLICATION (APPLICATION_ID,APPLICATION_NAME,DESCRIPTION, BU_ID, GU_ID, HANDBOOK_URL) values (1,'OEBS','n/a',1,1,'n/a');
Insert into CTUSR.APPLICATION (APPLICATION_ID,APPLICATION_NAME,DESCRIPTION, BU_ID, GU_ID, HANDBOOK_URL) values (2,'Siebel','n/a',1,1,'n/a');
Insert into CTUSR.APPLICATION (APPLICATION_ID,APPLICATION_NAME,DESCRIPTION, BU_ID, GU_ID, HANDBOOK_URL) values (3,'VoIP Switch','n/a',1,1,'n/a');
Insert into CTUSR.APPLICATION (APPLICATION_ID,APPLICATION_NAME,DESCRIPTION, BU_ID, GU_ID, HANDBOOK_URL) values (4,'DTV Activation','n/a',1,1,'n/a');
