REM INSERTING into SERVICE_ENGINE
Insert into CTUSR.SERVICE_ENGINE (ENGINE_ID,ENGINE_TYPE,ENGINE_NAME,ENGINE_URL) values (1,'JVM','ORACLE JVM','n/a');
Insert into CTUSR.SERVICE_ENGINE (ENGINE_ID,ENGINE_TYPE,ENGINE_NAME,ENGINE_URL) values (2,'BPEL','ORACLE BPEL ENGINE','n/a');
Insert into CTUSR.SERVICE_ENGINE (ENGINE_ID,ENGINE_TYPE,ENGINE_NAME,ENGINE_URL) values (3,'OSB','ORACLE ESB ENGINE','n/a');
Insert into CTUSR.SERVICE_ENGINE (ENGINE_ID,ENGINE_TYPE,ENGINE_NAME,ENGINE_URL) values (4,'ORADB','ORACLE DB ENGINE','n/a');
Insert into CTUSR.SERVICE_ENGINE (ENGINE_ID,ENGINE_TYPE,ENGINE_NAME,ENGINE_URL) values (5,'ORAXDB','ORACLE XDB DB XDK','n/a');
