--------------------------------------------------------
--  File created - Tuesday-February-21-2012   
--------------------------------------------------------
REM INSERTING into OBJECT_PARAMETER
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (1,1,1,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (2,2,2,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (3,3,3,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (4,4,4,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (5,5,5,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (6,6,6,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (7,7,7,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (8,8,8,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (9,9,9,'Y',1);
Insert into CTUSR.OBJECT_PARAMETER (OBJECTPARAMETER_ID,OBJECT_ID,PARAMETER_ID,OBJPRIMARY_KEY,PARAMETER_ORDER) values (10,10,10,'Y',1);
