REM INSERTING into ENDPOINT
Insert into CTUSR.ENDPOINT(ENDPOINT_ID, ENDPOINTYPE_ID, PROTOCOL_ID,ENDPOINT_URL,DESCRIPTION) values(	1	,1	,1, 'SIFAUDIT.SIFAUDIT_INBOUND_XML_ERR'  ,'SIFAUDIT Error Inbound AQ'	);
