--REM INSERTING into SERVICE

--CTU common
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (0,10,'NOP',4,'NOP','NOP','192.198.10.101','CTUPLADEV01');

-- SERVICE BROKER common
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4003,7,'PS_PLA_GenericAdapter_Inbound',3,'PS_PLA_GenericAdapter_Inbound','PS_PLA_GenericAdapter_Inbound','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4004,7,'PS_PLA_GenericAdapterSynch',3,'PS_PLA_GenericAdapterSynch','PS_PLA_GenericAdapterSynch','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4005,7,'PS_PLA_GenericAdapter_Outbound',3,'PS_PLA_GenericAdapter_Outbound','PS_PLA_GenericAdapter_Outbound','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4006,7,'PS_Generic_Database_Adapter',3,'PS_Generic_Database_Adapter','PS_Generic_Database_Adapter','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4007,7,'PS_FTP_Protocol_Adapter',3,'PS_FTP_Protocol_Adapter','PS_FTP_Protocol_Adapter','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4008,7,'PS_JMS_Protocol_Adapter',3,'PS_JMS_Protocol_Adapter','PS_JMS_Protocol_Adapter','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4009,7,'PS_Generic_Soap_Adapter',3,'PS_Generic_Soap_Adapter','PS_Generic_Soap_Adapter','NA','NA');
Insert into CTUSR.SERVICE (SERVICE_ID, SERVICEMODEL_ID, TASK, ENGINE_ID,    SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_URL, SERVICE_HOST) values (4010,7,'ServiceBroker',3,'ServiceBroker','ServiceBroker','NA','NA');
