REM INSERTING into PROTOCOL
Insert into CTUSR.PROTOCOL (PROTOCOL_ID,PROTOCOL_NAME,PROTOCOL_VERSION) values (1,'JMS/MQ','n/a');
Insert into CTUSR.PROTOCOL (PROTOCOL_ID,PROTOCOL_NAME,PROTOCOL_VERSION) values (2,'SOAP','1.1');
Insert into CTUSR.PROTOCOL (PROTOCOL_ID,PROTOCOL_NAME,PROTOCOL_VERSION) values (3,'SOAP','1.2');
Insert into CTUSR.PROTOCOL (PROTOCOL_ID,PROTOCOL_NAME,PROTOCOL_VERSION) values (4,'HTTP','1.1');
