REM INSERTING into SERVICE_MODEL
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (1,'Application service','A generic category used to represent services that contain logic derived from a solution or technology platform. Services are generally distinguished as application services when creating service abstraction layers.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (2,'Business service','A generic category used to represent services that contain business logic. When establishing specialized service layers, services that fall into the business service layer are collectively referred to as business services. However, individually these services are classified as entity-centric or task-centric business services.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (3,'Controller service','A service that composes others. Variations of this model exist, depending on the position of the controller in the composition hierarchy. The parent controller service can be classified as the master controller and a service that composes a subset of a larger composition can be labeled a sub-controller.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (4,'Coordinator services','Three service models are derived from the concept of coordination: the coordinator, the atomic transaction coordinator, and the business activity coordinator. All three models are specific to the WS-Coordination specification and related protocols.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (5,'Entity-centric business service','A business process-agnostic variation of the business service that represents one or more related business entities. This type of service is created when establishing a business service layer.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (6,'Hybrid service','A service that contains both business and application logic. Most services created as part of traditional distributed solutions fall into this category. When organizing services into abstraction layers, hybrid services are considered part of the application service layer.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (7,'Integration service','An application service that also acts as an endpoint to a solution environment for cross-application integration purposes.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (8,'Process service','A service that represents a business process as implemented by an orchestration platform and described by a process definition. Process services reside in the orchestration service layer.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (9,'Task-centric business service','A business process-specific variation of the business service that represents an atomic unit of process logic. Task-centric services are different from process services in that the process logic is provided by the underlying service logic, not by a separate process definition.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (10,'Utility service','A service that offers reusable logic. This category is primarily intended for the classification of solution-agnostic application services. However, it also can be used to refer to reusable business services.');
Insert into CTUSR.SERVICE_MODEL (SERVICEMODEL_ID,SERVICE_MODEL,MODEL_DESCRIPTION) values (11,'Wrapper service','A type of integration service that encapsulates and exposes logic residing within a legacy system. Wrapper services are commonly provided by legacy system vendors and therefore frequently introduce non-standardized interfaces.');
