--------------------------------------------------------
--  File created - Monday-February-20-2012    
--------------------------------------------------------
REM INSERTING into RULE_VERIFICATION
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (1,'=');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (2,'>');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (3,'<');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (4,'LIKE');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (5,'ISLENMORE');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (6,'ISLENLESS');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (7,'ISNULL');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (8,'ISNOTNULL');
Insert into CTUSR.RULE_VERIFICATION (RULEVERIFICATION_ID,RULE_VERIFICATION) values (9,'<>');
