
CREATE USER CTUSR
  IDENTIFIED BY "CTUSR"
  DEFAULT TABLESPACE CTUSR_RUNTIME
  TEMPORARY TABLESPACE CTUSR_TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;


  GRANT RESOURCE TO CTUSR;
  GRANT CONNECT  TO CTUSR;

  -- 1 Tablespace Quotas for CTUSR 
  ALTER USER CTUSR QUOTA UNLIMITED ON CTUSR_RUNTIME;
  ALTER USER "CTUSR" DEFAULT ROLE "RESOURCE","CONNECT";
  
  GRANT CREATE SESSION   TO CTUSR;   
  GRANT CREATE SEQUENCE  TO CTUSR;
  GRANT CREATE PROCEDURE TO CTUSR;
  GRANT CREATE TABLE     TO CTUSR;
  GRANT CREATE VIEW      TO CTUSR;
  GRANT DROP ANY TYPE    TO CTUSR;
  GRANT DROP ANY VIEW    TO CTUSR;
  GRANT ALTER ANY TYPE   TO CTUSR;
  GRANT CREATE ANY INDEX TO CTUSR;
  GRANT CREATE ANY TABLE TO CTUSR;
  GRANT CREATE DIMENSION TO CTUSR;
  GRANT CREATE INDEXTYPE TO CTUSR;
  GRANT DELETE ANY TABLE TO CTUSR;
  GRANT DROP ANY SYNONYM TO CTUSR;
  GRANT DROP ANY TRIGGER TO CTUSR;
  -- Grants with ADMIN Privs
  GRANT GATHER_SYSTEM_STATISTICS TO CTUSR WITH ADMIN OPTION;
  GRANT XDBADMIN                 TO CTUSR WITH ADMIN OPTION;
  GRANT CREATE JOB               TO CTUSR WITH ADMIN OPTION;
  
  -- SELECT grants CTUSR TO Collection sources
  GRANT CREATE TYPE TO CTUSR;