
 
 --[GLOBAL:CTUSR GRANT EXECUTE ON :  SIFAUDIT.*]

GRANT SELECT, INSERT, DELETE ON SIFAUDIT.SIF_AUDIT_SYSPARAM TO CTUSR;                         
GRANT SELECT, INSERT, DELETE ON SIFAUDIT.SIF_EVENT_LOG      TO CTUSR;                        
GRANT SELECT, INSERT, DELETE ON SIFAUDIT.SIF_EVENT_STATS    TO CTUSR;                        
GRANT SELECT, INSERT, DELETE ON SIFAUDIT.SR_EVENTPROC_LOG   TO CTUSR;                  
GRANT SELECT, INSERT, DELETE ON SIFAUDIT.SR_MESSAGE_LOG     TO CTUSR;                            
